import type { Product } from "@/lib/types"

// Use the actual image path that we know exists
const productImagePath = "/images/denike-background.png"
const hairModelImage = "/images/hair-model.png"
const hairCollectionImage = "/images/hair-collection.png"

export const products: Product[] = [
  // Hair products
  {
    id: "premium-bob-wig-black-burgundy",
    name: "Premium Bob Wig - Black/Burgundy",
    description:
      "This elegant bob wig features a stunning black to burgundy ombre effect. Made with high-quality synthetic fibers that look and feel like natural hair. The pre-styled bob cut offers a sophisticated look that frames the face beautifully.",
    price: 149.99,
    images: [hairModelImage, hairModelImage, hairModelImage],
    category: "Hair",
    tags: ["Wig", "Bob", "Ombre", "Burgundy"],
    colors: ["Black/Burgundy"],
    material: "Premium synthetic fiber",
    madeIn: "Handcrafted with care",
    care: "Gentle wash with wig shampoo, air dry",
    isNew: true,
  },
  {
    id: "colored-hair-bundle-burgundy",
    name: "Colored Hair Bundle - Burgundy",
    description:
      "Add a pop of color to your look with our premium burgundy hair bundle. This high-quality hair extension is perfect for creating vibrant, eye-catching styles. Each bundle is carefully selected for consistent color and texture.",
    price: 89.99,
    images: [hairCollectionImage, hairCollectionImage],
    category: "Hair",
    tags: ["Bundle", "Extension", "Burgundy"],
    colors: ["Burgundy"],
    material: "Premium synthetic fiber",
    madeIn: "Carefully selected and processed",
    care: "Gentle wash, avoid heat styling",
    isBestseller: true,
  },
  {
    id: "colored-hair-bundle-orange",
    name: "Colored Hair Bundle - Orange",
    description:
      "Make a bold statement with our vibrant orange hair bundle. Perfect for creating unique styles and adding a splash of color. Each bundle provides full coverage and blends seamlessly with your natural hair.",
    price: 89.99,
    images: [hairCollectionImage, hairCollectionImage],
    category: "Hair",
    tags: ["Bundle", "Extension", "Orange"],
    colors: ["Orange"],
    material: "Premium synthetic fiber",
    madeIn: "Carefully selected and processed",
    care: "Gentle wash, avoid heat styling",
  },
  {
    id: "colored-hair-bundle-blonde",
    name: "Colored Hair Bundle - Blonde",
    description:
      "Achieve that perfect blonde look with our premium blonde hair bundle. This high-quality extension provides natural-looking volume and length. Each bundle is carefully processed for consistent color and texture.",
    price: 99.99,
    images: [hairCollectionImage, hairCollectionImage],
    category: "Hair",
    tags: ["Bundle", "Extension", "Blonde"],
    colors: ["Blonde"],
    material: "Premium synthetic fiber",
    madeIn: "Carefully selected and processed",
    care: "Gentle wash, avoid heat styling",
  },
  // Original products
  {
    id: "handcrafted-leather-tote",
    name: "Handcrafted Leather Tote",
    description:
      "A spacious and elegant tote bag handcrafted from premium full-grain leather. Perfect for everyday use, this tote features a minimalist design with ample interior space for all your essentials.",
    price: 189.99,
    compareAtPrice: 229.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Accessories",
    tags: ["Leather", "Handcrafted", "Tote", "Bag"],
    colors: ["Black", "Brown", "Tan"],
    material: "Full-grain leather",
    madeIn: "Handcrafted in small batches",
    care: "Clean with leather conditioner",
    onSale: true,
  },
  {
    id: "signature-silk-scarf",
    name: "Signature Silk Scarf",
    description:
      "Our signature silk scarf features a unique hand-painted design exclusive to Denikesignatures. Made from 100% pure silk, this versatile accessory adds elegance to any outfit.",
    price: 79.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Accessories",
    tags: ["Silk", "Scarf", "Handpainted"],
    colors: ["Multicolor", "Blue", "Red"],
    material: "100% pure silk",
    madeIn: "Hand-painted by artisans",
    care: "Dry clean only",
    isNew: true,
  },
  {
    id: "artisan-woven-dress",
    name: "Artisan Woven Dress",
    description:
      "This stunning dress is meticulously woven by skilled artisans using traditional techniques. The unique texture and flowing silhouette create a flattering and comfortable fit for all occasions.",
    price: 249.99,
    compareAtPrice: 299.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Clothing",
    tags: ["Dress", "Woven", "Artisan"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Natural", "Indigo", "Terracotta"],
    material: "Organic cotton and linen blend",
    madeIn: "Handwoven by master artisans",
    care: "Hand wash cold, lay flat to dry",
    onSale: true,
  },
  {
    id: "embroidered-linen-blouse",
    name: "Embroidered Linen Blouse",
    description:
      "A lightweight linen blouse featuring intricate hand embroidery. The relaxed fit and breathable fabric make this a perfect piece for warm weather or layering.",
    price: 129.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Clothing",
    tags: ["Blouse", "Linen", "Embroidered"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Cream", "Sage"],
    material: "100% linen",
    madeIn: "Hand-embroidered details",
    care: "Machine wash cold, gentle cycle",
    isNew: true,
  },
  {
    id: "handwoven-straw-hat",
    name: "Handwoven Straw Hat",
    description:
      "Our signature straw hat is handwoven by skilled artisans using sustainable materials. The wide brim provides excellent sun protection while the adjustable inner band ensures a perfect fit.",
    price: 69.99,
    images: [productImagePath, productImagePath],
    category: "Accessories",
    tags: ["Hat", "Straw", "Handwoven"],
    sizes: ["S/M", "L/XL"],
    material: "Natural straw",
    madeIn: "Handwoven by artisans",
    care: "Spot clean only, store in cool dry place",
  },
  {
    id: "organic-cotton-jumpsuit",
    name: "Organic Cotton Jumpsuit",
    description:
      "This versatile jumpsuit is crafted from soft organic cotton with a relaxed silhouette. Features adjustable straps, side pockets, and a comfortable elastic waistband for an effortless yet stylish look.",
    price: 159.99,
    compareAtPrice: 189.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Clothing",
    tags: ["Jumpsuit", "Organic", "Cotton"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Olive", "Navy"],
    material: "100% organic cotton",
    madeIn: "Ethically produced",
    care: "Machine wash cold, tumble dry low",
    onSale: true,
  },
  {
    id: "hand-tooled-leather-wallet",
    name: "Hand-Tooled Leather Wallet",
    description:
      "A beautifully crafted wallet featuring hand-tooled designs on premium vegetable-tanned leather. This compact wallet includes card slots, a bill compartment, and RFID protection.",
    price: 89.99,
    images: [productImagePath, productImagePath],
    category: "Accessories",
    tags: ["Wallet", "Leather", "Handcrafted"],
    colors: ["Brown", "Black"],
    material: "Vegetable-tanned leather",
    madeIn: "Hand-tooled by master craftsmen",
    care: "Treat with leather conditioner as needed",
  },
  {
    id: "artisan-ceramic-earrings",
    name: "Artisan Ceramic Earrings",
    description:
      "These statement earrings are handcrafted from ceramic and finished with 14k gold-filled findings. Each pair is unique with subtle variations in the glaze, making them truly one-of-a-kind.",
    price: 59.99,
    images: [productImagePath, productImagePath],
    category: "Accessories",
    tags: ["Earrings", "Ceramic", "Handmade"],
    colors: ["Blue", "Terracotta", "White"],
    material: "Ceramic with 14k gold-filled findings",
    madeIn: "Handcrafted by ceramic artists",
    care: "Store in jewelry box, avoid water exposure",
    isNew: true,
  },
  {
    id: "handcrafted-leather-boots",
    name: "Handcrafted Leather Boots",
    description:
      "These timeless boots are handcrafted from full-grain leather with a durable Goodyear welt construction. Designed for comfort and longevity, they feature a cushioned insole and slip-resistant rubber outsole.",
    price: 279.99,
    compareAtPrice: 329.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Footwear",
    tags: ["Boots", "Leather", "Handcrafted"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Brown", "Black"],
    material: "Full-grain leather",
    madeIn: "Handcrafted by master bootmakers",
    care: "Clean with leather cleaner, condition regularly",
    onSale: true,
  },
  {
    id: "woven-bamboo-sandals",
    name: "Woven Bamboo Sandals",
    description:
      "These lightweight sandals feature handwoven bamboo straps and a comfortable cork footbed. Perfect for warm weather, they provide both style and comfort with sustainable materials.",
    price: 79.99,
    images: [productImagePath, productImagePath],
    category: "Footwear",
    tags: ["Sandals", "Bamboo", "Sustainable"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Natural", "Black"],
    material: "Bamboo and cork",
    madeIn: "Handwoven by skilled artisans",
    care: "Wipe clean with damp cloth",
    isNew: true,
  },
  {
    id: "linen-wide-leg-pants",
    name: "Linen Wide-Leg Pants",
    description:
      "These breezy wide-leg pants are made from premium linen with a high waist and flowing silhouette. The lightweight fabric and relaxed fit make them perfect for warm weather and casual elegance.",
    price: 119.99,
    images: [productImagePath, productImagePath, productImagePath],
    category: "Clothing",
    tags: ["Pants", "Linen", "Wide-Leg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Oatmeal"],
    material: "100% linen",
    madeIn: "Ethically produced",
    care: "Machine wash cold, hang to dry",
  },
  {
    id: "hand-painted-silk-kimono",
    name: "Hand-Painted Silk Kimono",
    description:
      "This luxurious kimono features hand-painted designs on 100% silk. Each piece is a wearable work of art, perfect as a statement layer or elegant loungewear.",
    price: 249.99,
    images: [productImagePath, productImagePath],
    category: "Clothing",
    tags: ["Kimono", "Silk", "Hand-Painted"],
    sizes: ["One Size"],
    colors: ["Multicolor"],
    material: "100% silk",
    madeIn: "Hand-painted by textile artists",
    care: "Dry clean only",
    isNew: true,
  },
]

